@api = http://localhost:8000
@token_root=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290QHJvb3QuY29tIiwiYXV0aG9yaXRpZXMiOlsicm9vdCJdLCJpYXQiOjE3NzQwMjkzNDEsImV4cCI6MTc3NDA1ODE0MX0.RokBBG_xRITmvfR3UmMNkMuxJNyBZecyBUVgu3zZS5k9cyCgLwC7fqvKOX3vdruTZ3fCWJqV1_ASchgfE0ksJw

@token_adim=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJhdXRob3JpdGllcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzM5NDMxMDgsImV4cCI6MTc3Mzk3MTkwOH0.CfuhXkiQt-81jzx-FHqsa2xDVGF0wuC7OMO8KgFfOMZduAyZN8TFgS9OAHq2qtVUZJz7sPx_911WkhzC4lwUug

### Login com root
POST {{api}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "root@root.com",
    "senha": "123456"
}

### Login com admin
POST {{api}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@admin.com",
    "senha": "123456"
}

### Obter perfis (root)
GET {{api}}/root/perfil
Authorization: Bearer {{token_root}}

### Obter usuários
GET {{api}}/root/usuario
Authorization: Bearer {{token_root}}

### Cadastrar usuário/pessoa admin
POST {{api}}/root/usuario
Content-Type: application/json
Authorization: Bearer {{token_root}}

{
    "email": "admin@admin.com",
    "nome": "Administrador",
    "cpf": "75571456078",
    "celular": "75571456078",
    "perfis": [2]
}

### Listar status possíveis para projetos
GET {{api}}/root/status-projeto
Authorization: Bearer {{token_root}}

### Listar projetos
GET {{api}}/admin/projeto
Authorization: Bearer {{token_root}}

### Listar projetos pelo status
GET {{api}}/admin/projeto/status/1
Authorization: Bearer {{token_root}}

### Criar projetos
POST {{api}}/admin/projeto
Content-Type: application/json
Authorization: Bearer {{token_root}}

{
    "nome": "Projeto 2",
    "descricao": "2º Projeto",
    "membroGerente": {
        "email": "gerente@gerente.com",
        "senha": "123456",
        "nome": "Admin 2",
        "cpf": "03533093034",
        "celular": "61999350783",
        "perfis": [4]
    },
    "dataInicio": "2026-01-01",
    "dataPrevisaoTermino": "2026-05-10",
    "idStatusAtual": 1,
    "orcamentoTotal": 500100
}

### Listar projeto especifico
GET {{api}}/admin/projeto/8
Authorization: Bearer {{token_root}}

### Alterar andamento de projeto especifico
PUT {{api}}/admin/projeto/4/andamento
Content-Type: application/json
Authorization: Bearer {{token_root}}

{
    "idNovoStatus": 7
}

### Obter membros de projeto especifico
GET {{api}}/admin/projeto/8/membro
Content-Type: application/json
Authorization: Bearer {{token_root}}

### Adicionar membro com pessoa existente em projeto especifico
POST {{api}}/admin/projeto/8/membro
Content-Type: application/json
Authorization: Bearer {{token_root}}

{
    "idPessoa": 17,
    "idAtribuicao": 2
}

### Adicionar novo membro em projeto especifico
POST {{api}}/admin/projeto/8/membro
Content-Type: application/json
Authorization: Bearer {{token_root}}

{
    "idAtribuicao": 2,
    "email": "funcionario@funcionario.com",
    "nome": "Funcionário",
    "cpf": "07124866073",
    "celular": "61999350783",
    "perfis": [5]
}