spring.application.name=portfolios
server.port=8000

# secret usado para segurança do JWT
jwt.secret = "JWT_SECRET=bXlTdXBlclNlY3JldEtleUFxdWlFeGVtcGxvMTIzNDU2Nzg5MDEyMw=="

# 8 horas em milisegundos
jwt.token.expiration_in_millis=28800000
spring.profiles.active=${ACTIVE_PROFILE:dev}