spring.application.name=portfolios
server.port=8000
spring.datasource.url=jdbc:postgresql://ep-silent-haze-acbsrmot-pooler.sa-east-1.aws.neon.tech/portfolios?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_f0vhlwpESO1g
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# secret usado para segurança do JWT
jwt.secret = "JWT_SECRET=bXlTdXBlclNlY3JldEtleUFxdWlFeGVtcGxvMTIzNDU2Nzg5MDEyMw=="

# 8 horas em milisegundos
jwt.token.expiration_in_millis=28800000